
AWSTemplateFormatVersion:       2010-09-09
Description:                    "CloudFormation macro example IAM role for target account"
Parameters:
  SourceAccount:
    Description:                AccountId of source/Cloudformation account
    Type:                       String
    Default:                    222222222222
Resources:
  XAccountRole:
    Type:                       AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version:                2012-10-17
        Statement:
          - Effect:             Allow
            Principal:
              AWS:              !Sub "arn:aws:iam::${SourceAccount}:root"
            Action:             ['sts:AssumeRole']
      Path:                     /

  LambdaPolicy:
    Type:                       AWS::IAM::Policy
    Properties:
      PolicyName:               SSMAccess
      PolicyDocument:
        Version:                "2012-10-17"
        Statement:
          - Effect:             Allow
            Action:
              - "ssm:GetParameter"
            Resource:
              - "*"
      Roles:
        - !Ref XAccountRole
